server:
  port: 8090
#spring:
  #jpa:
    #defer-datasource-initialization: true
    #hibernate:
      #ddl-auto: update
    #properties:
      #hibernate:
        #dialect: org.hibernate.dialect.MySQL8Dialect

  #datasource:
    #url: jdbc:mysql://localhost:3306/ProductDb
    #username: root
    #password: vamsi
  #spring.jpa.database-platform = org.hibernate.dialect.PostgreSQL94Dialect
spring:
  profiles:
    active: dev
  liquibase:
    enabled: true
    #default-schema: ${db.schema}
    change-log: classpath:db/changelog/db_changeset_master.yml
  jpa:
    database: POSTGRESQL
    show-sql: true
    #database-platform : org.hibernate.dialect.PostgreSQL94Dialect
    properties:
      hibernate:
        ddl-auto: validate
        #dialect: org.hibernate.dialect.PostgreSQLDialect
        #default_schema: ${db.schema}
  #jpa:
    #database-platform: org.hibernate.dialect.PostgreSQL94Dialect
  datasource:
    url: jdbc:postgresql://localhost:5432/productdb
    username: postgres
    password: vamsi